### ISSUE TITLE
请问，出个带本地二进制包的可好

### ISSUE THREAD

**Issue by trockxi** [nick-zh/docker-kafka-eagle#1]
在线拉取二进制包，网络容易超时，自己制作的，运行后直接退出了，请帮忙看看
Dockerfile
FROM openjdk:8-jdk-alpine
ENV KE_HOME /opt/soft/kafka-eagle
ENV KE_CONF $KE_HOME/conf
ENV PATH $KE_HOME/bin:$PATH
ADD soft/* /opt/soft/
RUN echo "http://mirrors.aliyun.com/alpine/v3.7/main" > /etc/apk/repositories \
    && echo "http://mirrors.aliyun.com/alpine/v3.7/community" >> /etc/apk/repositories \
    && apk update \
    && apk add --no-cache bash tzdata \
    && rm -f /etc/localtime \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && chmod +x /opt/soft/kafka-eagle/bin/ke.sh
ENTRYPOINT ["sh","/opt/soft/startup.sh"]

startup.sh
#!/bin/bash
cd /opt/soft/kafka-eagle/bin
nohup ./ke.sh start &

**Comment by nick-zh** [comment]
Hey guys

Can you please translate what exactly fails for you? I have a issue open with kafka-eagle, because
this is not stable yet (my docker image):
https://github.com/smartloli/kafka-eagle/issues/75
I will see if i find time this week, but maybe you guys have another issue.

Cheers,
Nick

**Comment by nick-zh** [comment]
Closing since latest images shoud be working fine now
