### ISSUE TITLE
can provide docker settings

### ISSUE THREAD

**Issue by BrokenWingsIcarus** [nick-zh/docker-kafka-eagle#17]
need  docker settings to set docker configure。
有提供docker相关的环境变量配置吗。比如zokeeper的配置之类的,.能否花个时间在文档里写一下。。。。。

**Comment by nick-zh** [comment]
Hello
Yes you can use this file as reference to see which env variables you can pass:
https://github.com/nick-zh/docker-kafka-eagle/blob/main/system-config.properties
I hope this helps :v:

**Comment by BrokenWingsIcarus** [comment]
good.
