### ISSUE TITLE
error /usr/bin/env: ‘bash\r’: No such file or directory

### ISSUE THREAD

**Issue by BrokenWingsIcarus** [nick-zh/docker-kafka-eagle#18]
The error message suggests that the script you're invoking has embedded \r characters, which in turn suggests that it has Windows-style \r\n line endings instead of the \n-only line endings bash expects.

in win10 we get this error in run image. we fix it 

~~~
  vim ./entrypoint.sh
  :set fileformat=unix
  :wq
  docker-compose up
~~~

**Comment by nick-zh** [comment]
i think this is also cause if there is no `\n` on the last line, because `dos2unix` did not give a change. new images are being pushed, hope this resolves it
