### ISSUE TITLE
jmx 获取信息出错，缺少配置项。

### ISSUE THREAD

**Issue by tonyfud** [nick-zh/docker-kafka-eagle#7]
jmx 获取信息出错。

kafka-eagle_1  | java.lang.NullPointerException
kafka-eagle_1  | 2022-04-24 15:41:00 ERROR [Mx4jServiceImpl.Thread-16] - JMX service url[xxx:9393] create has error,msg is 
kafka-eagle_1  | java.lang.NullPointerException
kafka-eagle_1  | 2022-04-24 15:41:00 ERROR [Mx4jServiceImpl.Thread-16] - JMX service url[xxx:9393] create has error,msg is 
kafka-eagle_1  | java.lang.NullPointerException
kafka-eagle_1  | 2022-04-24 15:41:00 ERROR [KafkaServiceImpl.Thread-16] - Get kafka os memory from jmx has error, msg is null
kafka-eagle_1  | 2022-04-24 15:41:00 ERROR [KafkaServiceImpl.Thread-16] - Get kafka os memory from jmx has error, msg is null

需要配置文件里加入以下配置：

# kafka jmx uri
cluster.efak.jmx.uri=service:jmx:rmi:///jndi/rmi://%s/jmxrmi

**Comment by nick-zh** [comment]
@tonyfud images have been pushed, you can update them like this:
```
docker pull nickzurich/kafka-eagle:latest
```
or
```
docker pull nickzurich/kafka-eagle:2.1.0
```
depending on what tag you are using :v:

**Comment by tonyfud** [comment]
ok, thx
