### ISSUE TITLE
docker hub  的 laest 版本不是 最新的。 

### ISSUE THREAD

**Issue by tonyfud** [nick-zh/docker-kafka-eagle#8]
docker hub  的 laest 版本不是 最新的。 

拉下来是 2.0.9 版本的。

**Comment by nick-zh** [comment]
If you have used my images before with the `latest` tag, your local machine does not update automaticially when a new version of `latest ` is being pushed. This should resolve this:
```
docker pull nickzurich/kafka-eagle:latest
```
Let me know if that solves your problem :pray:
